name: Live 005 CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Use Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: "24.x"
          cache: "npm"

      - run: npm pkg delete scripts.prepare

      - name: Install dependencies
        run: npm ci

      - name: Linting
        run: npm run lint:ci

      - name: Typecheck
        run: npm run typecheck

      - name: Unit Tests
        run: npm run test:ci
